### ISSUE TITLE
Getting 'Unhandled Rejection (TypeError): Failed to fetch' error

### ISSUE THREAD

**Issue by shubham-aaic** [el10savio/TODO-Fullstack-App-Go-Gin-Postgres-React#35]
When I try to hit homepage I get  'Unhandled Rejection (TypeError): Failed to fetch' error. Please help me out.
![Screenshot from 2022-05-27 12-43-10](https://user-images.githubusercontent.com/98589467/170650226-0c046130-9362-43c9-9988-8bbd78aef80c.png)

**Comment by el10savio** [comment]
Hi @shubham-aaic,

Can you please make sure that you have the Go server & Postgres running. Looks like the above error is because it is unable to get a response back from the Go API server.

In the project root, you can use docker-compose to build the project

```
docker-compose build
docker-compose up
```

After running the above two commands you should see an output similar to the one below for `docker-compose ps` which means that all the services are up.

```
$ docker-compose ps
                        Name                                      Command               State            Ports         
-----------------------------------------------------------------------------------------------------------------------
todo-fullstack-app-go-gin-postgres-react_go-api_1      /go/bin/build ./wait-for-i ...   Up      0.0.0.0:8081->8081/tcp 
todo-fullstack-app-go-gin-postgres-react_postgres_1    docker-entrypoint.sh postgres    Up      0.0.0.0:50324->5432/tcp
todo-fullstack-app-go-gin-postgres-react_react-app_1   docker-entrypoint.sh npm start   Up      0.0.0.0:3000->3000/tcp 
```

**Comment by shubham-aaic** [comment]
Yes, go api server and postgres server are running properly you can refer below image. When I hit the api server locally it gives me response back. But it doesn't work in case of react.
![Screenshot from 2022-05-28 12-29-33](https://user-images.githubusercontent.com/98589467/170814453-927fbdb3-75df-45d3-a343-485fcbbba74e.png)
![Screenshot from 2022-05-28 12-27-55](https://user-images.githubusercontent.com/98589467/170814454-f982fa41-218a-474c-b1c8-ab09bed2b388.png)

**Comment by el10savio** [comment]
Alright, looks like we need to debug it out.

Can you add the following line to `componentDidMount()` in `frontend/src/components/todolist.js` and restart the docker-compose setup, after that can you please send the console log output once you open the page `http://localhost:3000/`  
and a snapshot of the docker-compose logs if the error pops up again.

```
componentDidMount() {
    fetch("http://localhost:8081/items")
      .then(res => res.json())
      .then(json => this.setState({ items: json.items }))
      .catch(err => console.log(err)); 
  }
```

**Comment by shubham-aaic** [comment]
I tried the code.Refer below screenshots!
![Screenshot from 2022-05-28 19-04-48](https://user-images.githubusercontent.com/98589467/170828827-d903e2a3-0f24-4f15-af28-d057c3cc852b.png)

![Screenshot from 2022-05-28 19-30-08](https://user-images.githubusercontent.com/98589467/170828819-44279152-76b9-4807-b85b-9bf54bda1a0a.png)

**Comment by shubham-aaic** [comment]
btw it says CORS error. I am running this application it on ec2-instance!
![image](https://user-images.githubusercontent.com/98589467/170830185-ee2923ca-625e-41c2-8fcd-2e226acc62d4.png)
